import type { AppPalette } from '../tokens/colors';
import type { GradientTokens } from '../tokens/gradients';
import type { ChartColorTokens } from '../tokens/charts';
import type { motionDuration, motionEasing } from '../tokens/motion';
import type { zIndex } from '../tokens/zIndex';
import type { opacity } from '../tokens/opacity';
import type { spacing } from '../tokens/spacing';
import type { borderRadius } from '../tokens/radii';
import type { typography } from '../tokens/typography';
import type { ThemeShadows } from '../tokens/shadows';

export type ThemeTokens = {
  isDark: boolean;
  colors: AppPalette;
  bg: string;
  bgElevated: string;
  surface: string;
  surfaceMuted: string;
  text: string;
  textMuted: string;
  textStrong: string;
  heading: string;
  label: string;
  border: string;
  borderSubtle: string;
  borderStrong: string;
  borderFocus: string;
  link: string;
  linkHover: string;
  tabBarBg: string;
  tabBarBorder: string;
  tabBarHeight: number;
  headerBg: string;
  headerBorder: string;
  inputBg: string;
  inputBorder: string;
  backdrop: string;
  shadows: ThemeShadows;
  semantic: {
    surface: string;
    backdrop: string;
    cardRadius: number;
    cardRadiusSmall: number;
    sheetRadius: number;
    cardShadow: ThemeShadows['card'];
    cardPadding: number;
    listMarginH: number;
    listGap: number;
  };
  spacing: typeof spacing;
  borderRadius: typeof borderRadius;
  typography: typeof typography;
  motion: {
    duration: typeof motionDuration;
    easing: typeof motionEasing;
    easeOut: typeof motionEasing.easeOut;
  };
  zIndex: typeof zIndex;
  opacity: typeof opacity;
  gradients: GradientTokens;
  chart: ChartColorTokens;
};
